### ISSUE TITLE
Child Selectors

### ISSUE THREAD

**Issue by hughsk** [css-modules/postcss-icss-composes#11]
Currently child selectors aren't picked up properly. Take this input file for example:

``` css
.simple {
  color: red;
}

.simple h1 {
  color: blue;
}
```

It yields:

``` css
._child_selectors__simple {
  color: red;
}

:local(.simple) h1 {
  color: blue;
}
```

When I'd expect the result to be:

``` css
._child_selectors__simple {
  color: red;
}

._child_selectors__simple h1 {
  color: blue;
}
```

Hopefully I'll get a chance to send through a PR sometime soon but if not here's a heads up :) Thanks!
