### ISSUE TITLE
Add `result.messages.dependency` support

### ISSUE THREAD

**Issue by michael-ciniawsky** [css-modules/postcss-icss-composes#166]
Adds composition files to webpack via `this.addDependency()` (`postcss-loader`) enabling watch mode for them

```css
.compose {
   composes: x from './path/to/file.css';
}
```

```js
postcss([ compose() ]).process(css, options)
  .then((result) => {
      result.messages // [ { type: 'dependency', file: 'path/to/file' } , ...]
  })
```
