### ISSUE TITLE
support proposed @extend spec

### ISSUE THREAD

**Issue by yoshuawuyts** [css-modules/postcss-icss-composes#3]
There's an [`@extend` spec proposal](https://tabatkins.github.io/specs/css-extend-rule/) in the works by @tabatkins. I'm not sure what the status is, but it's the best documented `@extend` implementation I've seen so far. It might be neat to support it rather than creating yet another implementation. Thanks!
### example

``` css
.error {
  color: red;
  border: thick dotted red;
}

.serious-error {
  @extend .error;
  font-weight: bold;
}
```
### links
- [`@extend` spec proposal](https://tabatkins.github.io/specs/css-extend-rule/)
- [`@extend` discussion](https://github.com/tabatkins/specs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+extend)

**Comment by tabatkins** [comment]
It is impossible to fully support `@extend` in a preprocessor; to do it properly, you need to be in the browser internals, so you can alter what types of things the browser matches on.

Doing it in a preprocessor, as Sass does, results in a combinatorial blow-up of selectors, even in relatively simple cases.  Sass uses a variety of heuristics to decide which small subset of the many possible selectors to actually emit, to maximize the usefulness of the feature while minimizing the selector blowout.  It still suffers a lot of bloat, tho.

**Comment by markdalgleish** [comment]
CSS Modules are not like a preprocessor. They compose multiple classes into a single identifier that's exposed in a JavaScript context, meaning we can achieve the same effect in every browser today without waiting for browsers to upgrade.

If browsers ever add support for `@extends`, there's no reason this couldn't work with CSS Modules.

**Comment by geelen** [comment]
Following on from Mark's comment, I thought it might be good to show an example of the difference.

---

So, the following Sass:

``` sass
.a {
  color: green;
}
.b {
  @extends .a;
  background-color: white;
}
```

outputs:

``` css
.a,.b {
  color: green;
}
.b {
  background-color: white;
}
```

for the following static HTML:

``` html
<div class="a">A</div>
<div class="b">B</div>
```

---

Doing the same with CSS Modules:

``` css
.a {
  color: green;
}
.b {
  extends: a;
  background-color: white;
}
```

becomes

``` css
:export {
  a: a_zxcz89x7cx;
  b: b_fg89gf97fg7 a_zxcz89x7cx;
}
.a_zxcz89x7cx {
  color: green;
}
.b_fg89gf97fg7 {
  background-color: white;
}
```

to be used in:

``` js
import styles from './styles.css'
elem.innerHTML = `
  <div class="${styles.a}">A</div>
  <div class="${styles.b}">B</div>
`
```

resulting in the following DOM:

``` html
<div class="a_zxcz89x7cx">A</div>
<div class="b_fg89gf97fg7 a_zxcz89x7cx">B</div>
```

So, the CSS isn't altered nor bloated by the `export` statement, instead multiple classes are being exported and injected into the DOM. It has a similar effect, and so far covers a lot of the use-cases I've seen for `@extends`, without the selector bloat. And it's totally pre-processable — it doesn't require a runtime polyfill.

Once in-browser `@extend` lands, there's no reason it can't be used alongside or instead of this, as Mark mentioned.
